# Generated by Django 3.2.9 on 2021-11-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_nombre', models.CharField(max_length=10, verbose_name='Unidad')),
            ],
        ),
    ]
