# Generated by Django 3.2.9 on 2021-11-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_cantidad', models.IntegerField(max_length=10, verbose_name='Cantidad')),
                ('pro_precio', models.IntegerField(max_length=10, verbose_name='Precio')),
                ('pro_total', models.IntegerField(max_length=10, verbose_name='Total')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
            options={
                'verbose_name': 'Proovedores',
            },
        ),
    ]
