# Generated by Django 3.2 on 2021-12-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20211122_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pro_cantidad',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pro_precio',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pro_total',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Total'),
        ),
    ]
