# Generated by Django 3.2.9 on 2022-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20211130_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pro_total',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Subtotal'),
        ),
    ]
