# Generated by Django 3.2 on 2021-12-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=20, verbose_name='Nombre del proyecto')),
                ('pro_fechainicio', models.DateField(verbose_name='Fecha de creación')),
                ('pro_fechafinal', models.DateField(verbose_name='Fecha de terminación')),
                ('pro_presupuesto', models.IntegerField(max_length=11, verbose_name='presupuesto')),
                ('pro_costo', models.PositiveIntegerField(max_length=11, verbose_name='Costo')),
                ('pro_gasto', models.PositiveIntegerField(max_length=11, verbose_name='Gasto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
