# Generated by Django 3.2.9 on 2021-11-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proovedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_cantidad', models.IntegerField(max_length=11, verbose_name='Cantidad')),
                ('co_fechaIngreso', models.DateField(verbose_name='FechaIngreso')),
                ('co_Total', models.PositiveIntegerField(max_length=11, verbose_name='Total')),
                ('prov_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proovedor.proovedor')),
            ],
            options={
                'verbose_name': 'Cantidad',
                'verbose_name_plural': 'Cantidades',
            },
        ),
    ]
