# Generated by Django 3.2.9 on 2021-11-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='co_cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='prov_id',
        ),
    ]
