# Generated by Django 3.2 on 2021-12-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20211130_1921'),
        ('compra', '0003_auto_20211130_1934'),
    ]

    operations = [
    ]
