# Generated by Django 3.2.9 on 2022-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_merge_0003_auto_20211130_1921_0003_auto_20211130_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='co_Total',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='costo total'),
        ),
    ]
