# Generated by Django 3.2 on 2022-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_compra_co_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='co_Total',
            field=models.PositiveIntegerField(max_length=11, verbose_name='Total'),
        ),
    ]
