# Generated by Django 3.2.9 on 2021-11-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proov_nombre', models.CharField(max_length=30, verbose_name='Nombre del proovedor')),
                ('proov_dni', models.IntegerField(max_length=15, verbose_name='Dni del proovedor')),
            ],
            options={
                'verbose_name': 'Proovedores',
            },
        ),
    ]
