# Generated by Django 3.2 on 2021-12-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proovedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='proov_dni',
            field=models.PositiveIntegerField(max_length=15, verbose_name='Dni del proovedor'),
        ),
    ]
